	.align 2
voicegroup191::
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_48, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_60, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_piano1_60, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_piano1_48, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_low, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_detuned_ep1_high, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 0, 193, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 0, 193, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 0, 193, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_low, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 0, 193, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 0, 193, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_72, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_72, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_timpani, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_60, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_84, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_84, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_trumpet_60, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tuba_39, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tuba_39, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_trumpet_72, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_french_horn_60, 255, 0, 193, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
	voice_directsound_alt 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 193, 127
